// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucwczfjisqgjzmdkkukk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjd2N6Zmppc3FnanptZGtrdWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzk4OTYsImV4cCI6MjA2MDY1NTg5Nn0.4TfnEl5zkblbq2KE9wNNIDeBh8jO5SNVK3AnaTYMMn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);